<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GuestBookMessageRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class GuestBookMessageRepository extends EntityRepository
{
    /**
     * @param int $amount
     */
    public function deleteOldMessages($amount)
    {
        $messages = $this->createQueryBuilder('m')
            ->orderBy('m.createdAt', 'ASC')
            ->setMaxResults($amount)
            ->getQuery()
            ->execute();
        foreach ($messages as $message) {
            $this->getEntityManager()->remove($message);
        }
        $this->getEntityManager()->flush();
    }
}
